// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjthowdyywptosrqcuxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqdGhvd2R5eXdwdG9zcnFjdXhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3ODE5ODEsImV4cCI6MjA2MzM1Nzk4MX0.h74DSAsgh8R0aRimtHX1euAbvEkqpSaABMEap2zxaOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);